#!/bin/bash

if [ -d /root ]
then
echo ""
else
mkdir /root
fi
cd /root/
if [[ -e /bin/instalacion N°1 ]]; then
instalar
exit
sleep 4s
else
 if [[ -e /bin/instalacion N°2 ]]; then
instalar
exit
sleep 4s
else
  if [[ -e /bin/instalacion N°3 ]]; then
instalar
exit
sleep 4s
else
   if [[ -e /bin/instalacion N°4 ]]; then
instalar
exit
sleep 4s
else
echo " "
clear
   fi
  fi
 fi
fi
clear
sleep 1s
echo -e "\033[1;31mATENCION USUARIO LEA DETENIDAMENTE (@Mr_Anonimo)!\033[0m"
echo -e "\033[1;36mESTE ES UN SCRIPT DE AYUDA PARA VPS COMPATIBLES PORFAVOR NO ADULTERAR LOS CODIGOS DE PROGRAMACION (SU VPS PUEDE SUFRIR DAÑOS SEVEROS CREDITOS Y AGRQDECIMIENTO > @Mr_Anonimo HACIE ENCUENTRAN EN TELEGRAM CUALQUIER DUDA O PREGUNTA PUEDEN LLEGAR AL CHAT !\033[1;31m"
read -p"ENTER PARA SEGUIR "
echo -e "\033[1;36mESTE SCRIPT SERA INSTALADO EN :
-----------------
DEBIAN
UBUNTU
-----------------
SI SU VPS NO CUMPLE CON EL SISTEMA OPERATIVO NECESARIO (NO INSTALAR)!!!\033[1;31m"
read -p"ENTER PARA SEGUIR "
echo -e "\033[0m"
sleep 1s
echo -e "\033[1;31mPREPARANDO SISTAMA DE INSTALACION EN 3 SEGUNDOS...\033[0m"
echo -e "\033[1;36m3...\033[0m"
sleep 1s
echo -e "\033[1;36m2...\033[0m"
sleep 1s
echo -e "\033[1;36m1...\033[0m"
sleep 1s
echo -e "\033[1;36mCOMENZANDO...\033[0m"
sleep 1s
echo -e "\033[1;36mPREPARANDO PARA DOWLOAD...\033[0m"
apt-get upgrade -y 1>/dev/null 2>/dev/null
echo  -e "\033[1;32m"
apt-get install zip -y
sleep 1s
echo  -e "\033[0m"
echo -e "\033[1;36mCOMENZANDO DOWLOAD...\033[0m"
cd /root/
sleep 1s
wget -O manager https://www.dropbox.com/s/v5xtqal2s6mnk2x/admmanager...zip?dl=0 -o /dev/null
sleep 4s
echo -e "\033[1;36mPREPARANDO ARCHIVOS...\033[0m"
sleep 4s
echo -e "\033[1;36mEXTRAINDO ARCHIVOS...\033[0m"
echo  -e "\033[1;32m"
unzip /root/manager
echo  -e "\033[0m"
sleep 4s
echo -e "\033[1;36mARCHIVOS EXTRAIDOS!...\033[0m"
sleep 4s
echo -e "\033[1;36mDANDO PERMISO A LOS ARCHIVOS...\033[0m"
mv -f /root/admmanager/* /bin/
chmod  -R 777 /bin/*
sleep 5s
echo -e "\033[1;36m YA CASI!!!...\033[0m"
sleep 4s
echo -e "\033[1;36mEJECUTANDO INSTALADOR\033[0m"
sleep 4s
echo -e "\033[1;36mAGUARDE...\033[0m"
rm -rf /root/manager*
sleep 1s
rm -rf /root/admmanager*
sleep 1s
rm -rf /root/inst*
sleep 1s
echo -e "\033[1;36mAGUARDE...\033[0m"
sleep 2s
echo -e "\033[1;31mLA INSTALACION INICIA EN  3 SEGUNDOS...\033[0m"
echo -e "\033[1;36m3...\033[0m"
sleep 1s
echo -e "\033[1;36m2...\033[0m"
sleep 1s
echo -e "\033[1;36m1...\033[0m"
sleep 1s
echo -e "\033[1;36m...\033[0m"
sleep 1s
echo -e "\033[1;36mINICIANDO...\033[0m"
instalar
sleep 2s
clear
exit